config/routes.rb
Rails.application.routes.draw do
  # get '/legal_pages'
  authenticate :user, ->(user) { user.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
  devise_for :users

  scope '(:locale)', locale: /en|fr|nl|de/ do
    root to: 'pages#home'
    resources :legal_pages, only: [:show], param: :slug
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # get 'welcome', to: "pages#welcome"
    # get 'solutions', to: "pages#solutions"
    get 'about', to: "pages#about"
    get 'values', to: "pages#values"
    get 'contact', to: "pages#contact"
    # get 'disclaimer', to: "pages#disclaimer"
    # get 'cgv', to: "pages#cgv"
    # get 'home', to: "pages#welcome"
    get 'new-home', to: "pages#home"
    # get 'atolo', to: "pages#welcome"
    # get 'training', to: "pages#solutions"
    # get 'consultancy', to: "pages#solutions"
    # get 'cookies', to: "pages#cookies"
    # get 'promotions', to: "pages#promotions"
    get 'thank_you', to: "pages#thank_you"
    get 'events', to: "pages#events"
    get 'summer_class', to: "pages#summer_class_2025"
    get 'newbies', to: "pages#newbies"
    get 'newbies_2024', to: "pages#newbies_2024"
    get 'eval', to: "pages#eval"
    get 'category/*category', to: "pages#category", as:'category'
    # get 'mockup', to: "pages#mock-up"

    resources :products, only: [ :create, :new, :show, :update, :edit, :destroy, :index ] do
      member do
        get :preview
      end
    end

    resources :messages, only: [ :create ]

  end

  # get 'fr', to: "pages#welcome"
  # get 'en', to: "pages#welcome"
  # get 'fr/atolo', to: "pages#welcome"
  # get 'en/atolo', to: "pages#welcome"

  # get 'training', to: "pages#solutions"
  # get 'fr/training', to: "pages#solutions"
  # get 'en/training', to: "pages#solutions"

  # get 'consultancy', to: "pages#solutions"
  # get 'fr/consultancy', to: "pages#solutions"
  # get 'en/consultancy', to: "pages#solutions"

  # get 'communicatie', to: redirect('/nl/solutions#communication-solutions')
  # get 'fr/communication', to: redirect('/fr/solutions#communication-solutions')
  # get 'en/communication', to: redirect('/solutions#communication-solutions')

  # get 'taal', to: redirect('/nl/solutions#languages-solutions')
  # get 'fr/langues', to: redirect('/fr/solutions#languages-solutions')
  # get 'en/languages', to: redirect('/solutions#languages-solutions')

  # get 'onze-aanpak', to: redirect('/nl/about')
  # get 'fr/notre-approche', to: redirect('/fr/about')
  # get 'en/our-approach', to: "pages#about"
  # get 'over-ons', to: redirect('/nl/about')
  # get 'fr/equipe', to: redirect('/fr/about#team-anchor')
  # get 'en/team', to: redirect('/about#team-anchor')

  # get 'atolo-pro-bono', to: redirect('/about#probono-anchor')
  # get 'fr/atolo-pro-bono', to: redirect('/fr/about#probono-anchor')
  # get 'nl/atolo-pro-bono', to: redirect('/nl/about#probono-anchor')
  # get 'en/atolo-pro-bono', to: redirect('/about#probono-anchor')

  # get 'onze-waarden', to: redirect('/nl/values')
  # get 'fr/our-values', to: redirect('/fr/values')
  # get 'en/our-values', to: "pages#values"

  # get 'fr/contact', to: redirect('/fr/contact')
  # get 'en/contact', to: "pages#contact"

  # # get 'cookies', to: "pages#cookies"
  # # get 'fr/disclaimer', to: "pages#disclaimer"
  # # get 'fr/cookies', to: "pages#cookies"
  # # get 'en/disclaimer', to: "pages#disclaimer"
  # # get 'en/cookies', to: "pages#cookies"

  # get 'test', to: redirect("http://www.webtrainer.be/ASP/Accent/company/cp135/")
  # get 'fr/test', to: redirect("http://www.webtrainer.be/ASP/Accent/company/cp135/")
  # get 'nl/test', to: redirect("http://www.webtrainer.be/ASP/Accent/company/cp135/")
  # get 'de/test', to: redirect("http://www.webtrainer.be/ASP/Accent/company/cp135/")

  get '*path', to: "pages#redirect"
end

app/views/shared/_contact-counter.html.erb
<section id="counter" class="wrapper style1 align-center counter-contact">
  <section id="contact" class="wrapper style1 align-left contact-in-counter" style="margin: auto;">
    <div class="inner">
      <header>
        <h2 class="align-center"><%= t('form.contact') %></h2>
      </header>
      <div class="content">
        <%= render 'shared/contact-form' %>
      </div>
    </div>
  </section>
</section>

app/views/shared/_contact-form.html.erb
<% if [259, 260, 261, 262].include?(@product&.id) %>
  <% message_title = Title.find_by_unique_key("summer_contact_form_message")&.translate(locale) %>
<% else %>
  <% message_title = Title.find_by_unique_key("contact_form_message")&.translate(locale) %>
<% end %>
<%= simple_form_for Message.new do |f| %>
  <h2><%= Title.find_by_unique_key("contact_form_title")&.translate(locale) %></h2>
  <%= f.input :name, label:Title.find_by_unique_key("contact_form_name")&.translate(locale)%>
  <%= f.input :company,  label:Title.find_by_unique_key("contact_form_company")&.translate(locale) %>
  <%= f.input :email,  label:Title.find_by_unique_key("contact_form_email")&.translate(locale) %>
  <%= f.input :phone,  label:Title.find_by_unique_key("contact_form_phone")&.translate(locale) %>
  <%= f.input :attachment, as: :file, label:Title.find_by_unique_key("contact_form_attachment")&.translate(locale) %>
  <%= f.input :content, label: message_title, as: :text %>
  <div class="field d-none">
    <input class="checkbot" id="checkbot" name="message[checkbot]" value="" />
    <label for="human"><%= t('form.human') %></label>
  </div>
  <div class="field d-none">
    <input class="checkmark" type="checkbox" id="human" name="message[robot]"/>
    <label for="human"><%= t('form.human') %></label>
  </div>
  <div class="field">
    <div class="g-recaptcha" data-sitekey="6Leq-ZYgAAAAAGFXLTnAWjkwonj4qbyyTlJ2ytVv" data-callback="onRecaptchaSuccess"
    data-expired-callback="onRecaptchaResponseExpiry"
    data-error-callback="onRecaptchaError"></div>
  </div>
  <%= f.submit Title.find_by_unique_key("contact_form_send")&.translate(locale), class:"primary contact-form-submit", id:"btnsubmit" , disabled: true%>
<% end %>

<script>
  let isRecaptchaValidated = false;

  function toggleRecaptchaFormMessage(type = "error", hide = false) {
    document.getElementById(`contact-form-${type}`).style.display = hide
      ? "none"
      : "inherit";
  }

  function onRecaptchaSuccess() {
    isRecaptchaValidated = true;
    document.getElementById("btnsubmit").disabled = false;
    document.getElementById("checkbot").value = "okay";
  }

  function onRecaptchaError() {
    // toggleRecaptchaFormMessage("error");
    // toggleRecaptchaFormMessage("success", true);
  }

  function onRecaptchaResponseExpiry() {
    // onRecaptchaError();
  }

  const recaptchaForm = document.getElementById("contact-form");
  recaptchaForm.addEventListener("submit", function (e) {
    console.log("toto");
    e.preventDefault();

    // failure
    if (!isRecaptchaValidated) {
      console.log('bot');
      // toggleRecaptchaFormMessage("error");
      // toggleRecaptchaFormMessage("success", true);
      return;
    }

    // success
    document.getElementById("contact-form").submit();
  });
</script>

app/views/shared/_counter.html.erb
_count

app/views/shared/_footer.html.erb
<!-- Footer -->
  <footer class="wrapper style1 footer-border">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-6 align-left small-font footer-address-large">
          <%= link_to root_path, :class => 'no-text-decoration' do %>
            <%= image_tag("atolo-logo/atolo.png", :class => "atolo-logo", :alt => "atolo") %>
          <% end %>
          <div class="row">
            <div class="col-xs-12 col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_languages")&.translate(locale)}", category_path(category: "languages"), class:"footer-link" %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_language_scan")&.translate(locale)}", eval_path, class:"footer-link" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_communication")&.translate(locale)}", category_path(category: "communication"), class:"footer-link" %>
            </div>
            <div class="col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_people")&.translate(locale)}", category_path(category: "people_and_culture"), class:"footer-link" %>

            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_about_us")&.translate(locale)}", about_path(), class:"footer-link d-none" %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_whats_new")&.translate(locale)}", summer_class_path, class:"footer-link d-none" %>
            </div>
          </div>
          <div class="row">
            <div class=" col-xs-12 col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_leadership")&.translate(locale)}", category_path(category: "leadership"), class:"footer-link" %>
            </div>
            <div class="col-xs-12 col-md-6">
              <%= link_to "#{Title.find_by_unique_key("navigation_contact")&.translate(locale)}", contact_path, class:"footer-link d-none" %>
            </div>
          </div>
        </div>

        <!-- <ul class="icons">
          <li><a class ="icon style2" href="https://www.linkedin.com/company/atolo/" target="_blank"><i class="fab fa-linkedin"></i></a></li>
          <li><a class ="icon style2" href="https://www.youtube.com/channel/UC9REEUoHZGDhSXGscOjSe8A" target="_blank"><i class="fab fa-youtube"></i></a></li>
          <li><a class ="icon style2" href="https://www.facebook.com/atololounge/" target="_blank"><i class="fab fa-facebook"></i></a></li>
          <li><a class ="icon style2" href="mailto:welcome@atolo.eu"><i class="fas fa-envelope"></i></a></li>
        </ul> -->
        <!-- <p>&copy; Terms of use.</p> -->
    <div class="col-xs-12 col-md-6">
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <div class="adress-title d-none">ATOLO SA/NV</div>
          <div class="d-none">
           Avenue de Tervurenlaan 36/18</br>
           1040 Brussels
           </div>
        </div>
        <div class="col-xs-12 col-md-6">
          <div class="adress-title">Atolo Sàrl</div>
          Rue du Petit-Chêne 18ter</br>
          1003 Lausanne
        </div>
      </div>
      <div class="row contact">
        <div class="col-xs-12 col-md-6">
          <div class="d-none">
            T. +32 2 609 50 90 </br>E. welcome@atolo.eu
          </div>
        </div>
        <div class="col-xs-12 col-md-6">
          T. +41 21 806 55 55 </br>T. +41 78 736 92 58</br>E. <a href="mailto:david@atolo.ch"> david@atolo.ch </a>
        </div>
      </div>
    </div>
  </div>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="copywrite">
          © <%= Time.now.year %> Atolo |
          <% LegalPage.all.each do |page| %>
            <%= link_to page.translate_title(I18n.locale).capitalize, legal_page_path(page.slug) %> |
          <% end %>
        </div>
      </div>
      <div class="offset-md-3 col-md-3">
        <div class="network-link">
          <a class ="icon" href="https://www.linkedin.com/company/atolo/" target="_blank">Follow us <i class="fab fa-linkedin-in"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>
  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

app/views/shared/_navbar-fixed.html.erb
  <!--==========================
    Header
  ============================-->
<header id="header-fixxed">
  <div class="navbar-inner">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
        <%= link_to welcome_path, :class => 'no-text-decoration' do %>
          <% image_tag("atolo-logo/atolo-new.png", :class => "atolo-logo", :alt => "atolo") %>
          <%= image_tag("atolo-logo/atolo.png", :class => "atolo-logo", :alt => "atolo", style:"margin-top: -18px;") %>
        <% end %>
      </div>

      <%= render 'shared/navigation' %>
    </div>
  </div>
</header>

app/views/shared/_navbar.html.erb
  <!--==========================
    Header
  ============================-->
<header id="header">
  <div class="navbar-inner">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
        <%= link_to welcome_path, :class => 'no-text-decoration' do %>
          <%= image_tag("atolo-logo/atolo.png", :class => "atolo-logo", :alt => "atolo", style:"margin-top: -18px;") %>
        <% end %>
      </div>

      <%= render 'shared/navigation' %>
    </div>
  </div>
</header>

app/views/shared/_navigation.html.erb
<nav id="nav-menu-container">
  <ul class="nav-menu">
    <li id="nav_welcome" class="">
      <%= link_to welcome_path do %>
        <%= t("navbar.home") %>
      <% end %>
    </li>
    <li id="nav_solutions" class="menu-has-children">
      <%= link_to solutions_path do %>
        <%= t("navbar.solutions") %>
      <% end %>
      <ul class="nav-menu-drop-down">
        <li id="nav_languages" class="offer-nav">
          <%= link_to solutions_path(:anchor => 'languages-solutions') do %>
            <%= t("navbar.languages_title") %>
          <% end %>
        </li>
        <li id="nav_eval" class="offer-nav">
          <%= link_to eval_path do %>
            <%= t("navbar.eval_title") %>
          <% end %>
        </li>
        <li id="nav_communication" class="offer-nav">
          <%= link_to solutions_path(:anchor => 'communication-solutions') do %>
            <%= t("navbar.communication_title") %>
          <% end %>
        </li>
        <li id="nav_engagement" class="offer-nav">
          <%= link_to solutions_path(:anchor => 'engagement-solutions') do %>
            <%= t("navbar.engagement_title") %>
          <% end %>
        </li>
      </ul>
    </li>
    <li id="nav_eval" class="offer-nav eval_visible">
      <%= link_to eval_path do %>
        <%= t("navbar.eval_title") %>
      <% end %>
    </li>
    <li id="nav_events">
      <%= link_to summer_class_path do %>
        <%= t("navbar.summer_class") %>
      <% end %>
    </li>
    <li id="nav_about">
      <%= link_to about_path do %>
        <%= t("navbar.about") %>
      <% end %>
      <ul class="nav-menu-drop-down">
        <li id="nav_team" class="about-nav">
          <%= link_to about_path(:anchor => 'team-anchor') do %>
            <%= t("navbar.team") %>
          <% end %>
        </li>
        <li id="nav_whereto" class="about-nav d-none">
          <%= link_to about_path(:anchor => 'location-anchor') do %>
            <%= t("navbar.whereto") %>
          <% end %>
        </li>
        <li id="nav_probono" class="about-nav">
          <%= link_to about_path(:anchor => 'probono-anchor') do %>
            <%= t("navbar.probono") %>
          <% end %>
        </li>
      </ul>
    </li>
    <li id="nav_values">
      <%= link_to values_path do %>
        <%= t("navbar.values") %>
      <% end %>
    </li>
    <li id="nav_contact">
      <% link_to contact_path do %>
        <%= t("navbar.contact") %>
      <% end %>
    </li>
    <li id="nav_internationalization">
      <div class="locale">
        <i class="fas fa-globe-europe"></i>
        <%= I18n.locale.upcase %>
      </div>
      <ul class="language-drop-down">
        <li class="mobile_language_drops">
          <%= link_to "English", url_for( :locale => 'en' ) %>
        </li>
        <li class="mobile_language_drops">
          <%= link_to "Français", url_for( :locale => 'fr' ) %>
        </li>
        <li class="mobile_language_drops">
          <%= link_to "Nederlands", url_for( :locale => 'nl' ) %>
        </li>
        <li class="mobile_language_drops">
          <%= link_to "Deutsch", url_for( :locale => 'de' ) %>
        </li>
      </ul>
    </li>
  </ul>
</nav>

app/views/shared/_new_navbar.html.erb
<% locale = I18n.locale %>
<% product = Rails.env.production? ? Product.find(258) : Product.last %>
<header id="new-header-fixed">
  <div class="container-fluid">

    <div id="logo" class="pull-left">
      <%= link_to root_path, :class => 'no-text-decoration' do %>
        <% image_tag("atolo-logo/atolo-new.png", :class => "atolo-logo", :alt => "atolo") %>
        <%= image_tag("atolo-logo/atolo.png", :class => "atolo-logo", :alt => "atolo") %>
      <% end %>
    </div>

    <nav id="nav-menu-container">
      <ul class="nav-menu">
        <li id="nav_red" class="">
          <%= link_to "#{Title.find_by_unique_key("navigation_languages")&.translate(locale)}", category_path(category: "languages"), class:"nav-link" %>
        </li>
        <li id="nav_blue" >
          <%= link_to "#{Title.find_by_unique_key("navigation_communication")&.translate(locale)}", category_path(category: "communication"), class:"nav-link" %>
        </li>
        <li id="nav_yellow" >
          <%= link_to "#{Title.find_by_unique_key("navigation_people")&.translate(locale)}", category_path(category: "people_and_culture"), class:"nav-link" %>
        </li>
        <li id="nav_green" >
          <%= link_to "#{Title.find_by_unique_key("navigation_leadership")&.translate(locale)}", category_path(category: "leadership"), class:"nav-link" %>
        </li>
        <li id="nav_eval">
          <%= link_to "#{Title.find_by_unique_key("navigation_language_scan")&.translate(locale)}", eval_path, class:"nav-link" %>
        </li>

        <li id="nav_about">
          <% link_to about_path do %>
            <%= Title.find_by_unique_key("navigation_about_us")&.translate(locale) %>
          <% end %>
          <ul class="nav-menu-drop-down">
            <li id="nav_team" class="about-nav">
              <%= link_to about_path(:anchor => 'team-anchor') do %>
                <%= Title.find_by_unique_key("navigation_team")&.translate(locale) %>
              <% end %>
            </li>
            <li id="nav_whereto" class="about-nav d-none">
              <%= link_to values_path(:anchor => 'location-anchor') do %>
                <%= Title.find_by_unique_key("navigation_our_values")&.translate(locale) %>
              <% end %>
            </li>
            <li id="nav_probono" class="about-nav">
              <%= link_to values_path(:anchor => 'location-anchor') do %>
                <%= Title.find_by_unique_key("navigation_our_values")&.translate(locale) %>
              <% end %>
            </li>
          </ul>
        </li>
        <li id="nav_events">
          <% link_to "#{Title.find_by_unique_key("navigation_whats_new")&.translate(locale)}", summer_class_path, class:"nav-link" %>
          <ul class="nav-menu-drop-down">
            <li id="nav_team" class="about-nav d-none">
              <%= link_to summer_class_path do %>
                Summer classes
              <% end %>
            </li>
            <li id="nav_team" class="about-nav">
              <a href="https://www.linkedin.com/pulse/from-language-barriers-business-breakthroughs-atolo-2wsae" target="_blank">
                <%= Title.find_by_unique_key("latest_success_story_link")&.translate(locale) %>
              </a>
            </li>
            <li id="nav_probono" class="about-nav d-none">
              <a href="https://www.eventbrite.be/e/bridging-the-generation-gap-how-to-lead-an-age-diverse-team-like-a-pro-tickets-1333817988509?aff=oddtdtcreator" target="_blank">
                <%= Title.find_by_unique_key("webinar_diversity_link")&.translate(locale) %>
              </a>
            </li>
          </ul>

        </li>
        <li id="nav_contact">
          <% link_to "#{Title.find_by_unique_key("navigation_contact")&.translate(locale)}", contact_path, class:"regular" %>
        </li>
        <li id="nav_internationalization">
          <div class="locale">
            <%= I18n.locale.upcase %>
          </div>
          <ul class="language-drop-down">
            <li class="mobile_language_drops">
              <%= link_to "English", url_for( :locale => 'en' ) %>
            </li>
            <li class="mobile_language_drops">
              <%= link_to "Français", url_for( :locale => 'fr' ) %>
            </li>
            <li class="mobile_language_drops">
              <%= link_to "Nederlands", url_for( :locale => 'nl' ) %>
            </li>
            <li class="mobile_language_drops">
              <%= link_to "Deutsch", url_for( :locale => 'de' ) %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>

  </div>

</header>

app/views/shared/_new_partners.html.erb
<section id="partners" class="wrapper style1 align-center">
  <h2><%= Title.find_by_unique_key("partners_title")&.translate(locale) %></h2>
  <div class="partners">
    <a href="https://www.alimento.be/" class="partner d-none" target="_blank">
      <%= image_tag("partners/Alimento.png", :alt => "image", :class => "") %>
    </a>
    <a href="https://www.febelfin-academy.be/" class="partner  d-none" target="_blank">
      <%= image_tag("partners/Febelfin.png", :alt => "image", :class => "") %>
    </a>
    <a href="https://www.fsma.be/" class="partner  d-none" target="_blank">
      <%= image_tag("partners/FSMA.jpg", :alt => "image", :class => "") %>
    </a>
    <a href="https://qfor.org/" class="partner  d-none" target="_blank">
      <%= image_tag("partners/Qfor.png", :alt => "image", :class => "") %>
    </a>

    <a href="https://saq.ch/" class="partner" target="_blank">
      <%= image_tag("partners/SAQ.png", :alt => "image", :class => "") %>
    </a>
    <a href="https://alice.ch/" class="partner" target="_blank">
      <%= image_tag("partners/FSEA.png", :alt => "image", :class => "") %>
    </a>
    <a href="https://www.vlaanderen.be/departement-werk-sociale-economie" class="partner d-none" target="_blank">
      <%= image_tag("partners/WSE.png", :alt => "image", :class => "") %>
    </a>
    <% if locale != :nl %>
      <a href="https://economie-emploi.brussels/conge-education-paye" class="partner  d-none" target="_blank">
        <%= image_tag("partners/SPF Eco & emploi.png", :alt => "image", :class => "") %>
      </a>
    <% else %>
      <a href="https://economie-werk.brussels/betaald-educatief-verlof" class="partner d-none" target="_blank">
        <%= image_tag("partners/Brussel Eco & werk.png", :alt => "image", :class => "") %>
      </a>
    <% end %>
    </a>


  </div>
</section>

app/views/shared/_new_testimonials.html.erb
<!-- Items -->
<div id="testimonials-anchor" class="testimonials-anchor"></div>
<section id="testimonials" class="wrapper style1 align-center">
  <div class="inner">
    <h2><%= Title.find_by_unique_key("testimonials_title")&.translate(locale) %></h2>
    <% classCarousel = @testimonials.count > 2 ? "card-carousel" : "two-card-carousel" %>
    <div class="owl-carousel owl-theme testimonial-cards onload-fade-in <%= classCarousel %>">
      <% @testimonials.each do |testimonial| %>
        <section class="testimonial-card">
          <div class="testimonial-card-logo">
            <%= image_tag(testimonial.logo_url, :alt => "image", :class => "testimonial-logo") %>
          </div>

          <p class="small-font"><%= eval("testimonial.content_#{locale}") %></p>
          <div class="testimonial-footer">
            <h3><%= testimonial.author %></h3>
            <h4><%= testimonial.company_name %></h4>
          </div>
        </section>
      <% end %>
    </div>
  </div>
</section>